########### Required #############
appID: 
appName: food-app
appOwner: food-app 
createdByEmail: armkay
accountId: 202533542038
region: ca-central-1
environment: dev 
auth_environment: dev 
deploymentBucketName: food-app-be-artifact
serviceName: be-customer
runtime: nodejs18.x

architecture: arm64
memorySize: 1024
timeout: 30
logRetentionInDays: 3

reservedConcurrency: 100
provisionedConcurrency: 0


restApiId: puwttty3ne
restApiRootResourceId: wc4kas1

authorizerId: rp4l4a